package sfa.model.viewobjects;

import java.math.BigDecimal;

import oracle.adf.model.binding.DCIteratorBinding;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;

import oracle.adf.model.BindingContext;

import sfa.model.viewobjects.common.CustomercontactsViewRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 15 09:54:44 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomercontactsViewRowImpl extends ViewRowImpl implements CustomercontactsViewRow {


    public static final int ENTITY_CUSTOMERCONTACTS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Contactid,
        Name,
        Title,
        Department,
        Workphone,
        Email,
        Buyingrole,
        Influencelevel,
        Isprimarycontact,
        Customeraccountid,
        ContactaddressView,
        AppointmentsView,
        InteractionView,
        NoteView,
        OpportunityView,
        TaskView,
        InviteesView,
        AppointmentsView1,
        BuyingRole1,
        InfluenceLevel1,
        CustomeraccountView1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CONTACTID = AttributesEnum.Contactid.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int WORKPHONE = AttributesEnum.Workphone.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int BUYINGROLE = AttributesEnum.Buyingrole.index();
    public static final int INFLUENCELEVEL = AttributesEnum.Influencelevel.index();
    public static final int ISPRIMARYCONTACT = AttributesEnum.Isprimarycontact.index();
    public static final int CUSTOMERACCOUNTID = AttributesEnum.Customeraccountid.index();
    public static final int CONTACTADDRESSVIEW = AttributesEnum.ContactaddressView.index();
    public static final int APPOINTMENTSVIEW = AttributesEnum.AppointmentsView.index();
    public static final int INTERACTIONVIEW = AttributesEnum.InteractionView.index();
    public static final int NOTEVIEW = AttributesEnum.NoteView.index();
    public static final int OPPORTUNITYVIEW = AttributesEnum.OpportunityView.index();
    public static final int TASKVIEW = AttributesEnum.TaskView.index();
    public static final int INVITEESVIEW = AttributesEnum.InviteesView.index();
    public static final int APPOINTMENTSVIEW1 = AttributesEnum.AppointmentsView1.index();
    public static final int BUYINGROLE1 = AttributesEnum.BuyingRole1.index();
    public static final int INFLUENCELEVEL1 = AttributesEnum.InfluenceLevel1.index();
    public static final int CUSTOMERACCOUNTVIEW1 = AttributesEnum.CustomeraccountView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustomercontactsViewRowImpl() {
    }

    /**
     * Gets Customercontacts entity object.
     * @return the Customercontacts
     */
    public EntityImpl getCustomercontacts() {
        return (EntityImpl) getEntity(ENTITY_CUSTOMERCONTACTS);
    }

    /**
     * Gets the attribute value for CONTACTID using the alias name Contactid.
     * @return the CONTACTID
     */
    public BigDecimal getContactid() {
        return (BigDecimal) getAttributeInternal(CONTACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACTID using the alias name Contactid.
     * @param value value to set the CONTACTID
     */
    public void setContactid(BigDecimal value) {
        setAttributeInternal(CONTACTID, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for TITLE using the alias name Title.
     * @return the TITLE
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as attribute value for TITLE using the alias name Title.
     * @param value value to set the TITLE
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT using the alias name Department.
     * @return the DEPARTMENT
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT using the alias name Department.
     * @param value value to set the DEPARTMENT
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for WORKPHONE using the alias name Workphone.
     * @return the WORKPHONE
     */
    public BigDecimal getWorkphone() {
        return (BigDecimal) getAttributeInternal(WORKPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for WORKPHONE using the alias name Workphone.
     * @param value value to set the WORKPHONE
     */
    public void setWorkphone(BigDecimal value) {
        setAttributeInternal(WORKPHONE, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for BUYINGROLE using the alias name Buyingrole.
     * @return the BUYINGROLE
     */
    public String getBuyingrole() {
        return (String) getAttributeInternal(BUYINGROLE);
    }

    /**
     * Sets <code>value</code> as attribute value for BUYINGROLE using the alias name Buyingrole.
     * @param value value to set the BUYINGROLE
     */
    public void setBuyingrole(String value) {
        setAttributeInternal(BUYINGROLE, value);
    }

    /**
     * Gets the attribute value for INFLUENCELEVEL using the alias name Influencelevel.
     * @return the INFLUENCELEVEL
     */
    public String getInfluencelevel() {
        return (String) getAttributeInternal(INFLUENCELEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for INFLUENCELEVEL using the alias name Influencelevel.
     * @param value value to set the INFLUENCELEVEL
     */
    public void setInfluencelevel(String value) {
        setAttributeInternal(INFLUENCELEVEL, value);
    }

    /**
     * Gets the attribute value for ISPRIMARYCONTACT using the alias name Isprimarycontact.
     * @return the ISPRIMARYCONTACT
     */
    public String getIsprimarycontact() {
        return (String) getAttributeInternal(ISPRIMARYCONTACT);
    }

    /**
     * Sets <code>value</code> as attribute value for ISPRIMARYCONTACT using the alias name Isprimarycontact.
     * @param value value to set the ISPRIMARYCONTACT
     */
    public void setIsprimarycontact(String value) {
        setAttributeInternal(ISPRIMARYCONTACT, value);
    }

    /**
     * Gets the attribute value for CUSTOMERACCOUNTID using the alias name Customeraccountid.
     * @return the CUSTOMERACCOUNTID
     */
    public BigDecimal getCustomeraccountid() {
        return (BigDecimal) getAttributeInternal(CUSTOMERACCOUNTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMERACCOUNTID using the alias name Customeraccountid.
     * @param value value to set the CUSTOMERACCOUNTID
     */
    public void setCustomeraccountid(BigDecimal value) {
        setAttributeInternal(CUSTOMERACCOUNTID, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ContactaddressView.
     */
    public Row getContactaddressView() {
        return (Row) getAttributeInternal(CONTACTADDRESSVIEW);
    }

    /**
     * Sets the master-detail link ContactaddressView between this object and <code>value</code>.
     */
    public void setContactaddressView(Row value) {
        setAttributeInternal(CONTACTADDRESSVIEW, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AppointmentsView.
     */
    public RowIterator getAppointmentsView() {
        return (RowIterator) getAttributeInternal(APPOINTMENTSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InteractionView.
     */
    public RowIterator getInteractionView() {
        return (RowIterator) getAttributeInternal(INTERACTIONVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link NoteView.
     */
    public RowIterator getNoteView() {
        return (RowIterator) getAttributeInternal(NOTEVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OpportunityView.
     */
    public RowIterator getOpportunityView() {
        return (RowIterator) getAttributeInternal(OPPORTUNITYVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TaskView.
     */
    public RowIterator getTaskView() {
        return (RowIterator) getAttributeInternal(TASKVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InviteesView.
     */
    public RowIterator getInviteesView() {
        return (RowIterator) getAttributeInternal(INVITEESVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AppointmentsView1.
     */
    public RowIterator getAppointmentsView1() {
        return (RowIterator) getAttributeInternal(APPOINTMENTSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BuyingRole1.
     */
    public RowSet getBuyingRole1() {
        return (RowSet) getAttributeInternal(BUYINGROLE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InfluenceLevel1.
     */
    public RowSet getInfluenceLevel1() {
        return (RowSet) getAttributeInternal(INFLUENCELEVEL1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> CustomeraccountView1.
     */
    public RowSet getCustomeraccountView1() {
        return (RowSet) getAttributeInternal(CUSTOMERACCOUNTVIEW1);
    }

    public void editPrimary(String cidStr) {
        System.out.println("Inside editPrimary");
        DCIteratorBinding dit = (DCIteratorBinding) BindingContext.getCurrent()
                                                                  .getCurrentBindingsEntry()
                                                                  .get("CustomercontactsView2Iterator");
        RowSet rs = dit.getViewObject().createRowSet(null);
        System.out.println(rs.hasNext());
        rs.reset();
        while (rs.hasNext()) {
            System.out.println("Inside while loop");
            Row r = rs.next();
            Object loopcid = r.getAttribute("Contactid");
            String loopCidStr = loopcid.toString();

            // Object loopaid=r.getAttribute("Customeraccountid");
            // String loopAidStr=loopcid.toString();
            if (loopCidStr.equals(cidStr)) {
                continue;
            } else {
                System.out.println("Inside else");
                r.setAttribute("Isprimarycontact", "N");
                //                DCBindingContainer bindings = (DCBindingContainer)BindingContext.getCurrent().getCurrentBindingsEntry();
                //                OperationBinding operationBinding = bindings.getOperationBinding(“Commit”);
                //                operationBinding.execute();

            }


        }
        System.out.println("Outside while");
        rs.closeRowSet();
    }

}

