package sfa.model.viewobjects;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 23 16:25:26 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NoteViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NoteViewImpl() {
    }
}

