package sfa.model.entities;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.*;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 11 16:11:26 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FilesImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Fileid,
        Filepath,
        Filename,
        Filetype,
        Oppid,
        Opportunity,
        Opportunity1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FILEID = AttributesEnum.Fileid.index();
    public static final int FILEPATH = AttributesEnum.Filepath.index();
    public static final int FILENAME = AttributesEnum.Filename.index();
    public static final int FILETYPE = AttributesEnum.Filetype.index();
    public static final int OPPID = AttributesEnum.Oppid.index();
    public static final int OPPORTUNITY = AttributesEnum.Opportunity.index();
    public static final int OPPORTUNITY1 = AttributesEnum.Opportunity1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FilesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("sfa.model.entities.Files");
    }


    /**
     * Gets the attribute value for Fileid, using the alias name Fileid.
     * @return the value of Fileid
     */
    public BigDecimal getFileid() {
        return (BigDecimal) getAttributeInternal(FILEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fileid.
     * @param value value to set the Fileid
     */
    public void setFileid(BigDecimal value) {
        setAttributeInternal(FILEID, value);
    }

    /**
     * Gets the attribute value for Filepath, using the alias name Filepath.
     * @return the value of Filepath
     */
    public String getFilepath() {
        return (String) getAttributeInternal(FILEPATH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Filepath.
     * @param value value to set the Filepath
     */
    public void setFilepath(String value) {
        setAttributeInternal(FILEPATH, value);
    }

    /**
     * Gets the attribute value for Filename, using the alias name Filename.
     * @return the value of Filename
     */
    public String getFilename() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Filename.
     * @param value value to set the Filename
     */
    public void setFilename(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for Filetype, using the alias name Filetype.
     * @return the value of Filetype
     */
    public String getFiletype() {
        return (String) getAttributeInternal(FILETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Filetype.
     * @param value value to set the Filetype
     */
    public void setFiletype(String value) {
        setAttributeInternal(FILETYPE, value);
    }

    /**
     * Gets the attribute value for Oppid, using the alias name Oppid.
     * @return the value of Oppid
     */
    public BigDecimal getOppid() {
        return (BigDecimal) getAttributeInternal(OPPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Oppid.
     * @param value value to set the Oppid
     */
    public void setOppid(BigDecimal value) {
        setAttributeInternal(OPPID, value);
    }

    /**
     * @return the associated entity OpportunityImpl.
     */
    public OpportunityImpl getOpportunity() {
        return (OpportunityImpl) getAttributeInternal(OPPORTUNITY);
    }

    /**
     * Sets <code>value</code> as the associated entity OpportunityImpl.
     */
    public void setOpportunity(OpportunityImpl value) {
        setAttributeInternal(OPPORTUNITY, value);
    }


    /**
     * @return the associated entity OpportunityImpl.
     */
    public OpportunityImpl getOpportunity1() {
        return (OpportunityImpl) getAttributeInternal(OPPORTUNITY1);
    }

    /**
     * Sets <code>value</code> as the associated entity OpportunityImpl.
     */
    public void setOpportunity1(OpportunityImpl value) {
        setAttributeInternal(OPPORTUNITY1, value);
    }


    /**
     * @param fileid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal fileid) {
        return new Key(new Object[] { fileid });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq= new SequenceImpl("COMMONSEQUENCE",getDBTransaction().getRootApplicationModule());
                BigDecimal noteid=new BigDecimal(seq.getSequenceNumber().toString());
                setFileid(noteid);
    }
}

