package sfa.model.viewobjects.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 15 09:57:30 IST 2021
// ---------------------------------------------------------------------
public interface CustomercontactsViewRow extends Row {
    void editPrimary(String cidStr);
}

