package sfa.model.viewobjects.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 23 16:27:17 IST 2021
// ---------------------------------------------------------------------
public interface NoteViewRow extends Row {
    void update();
}

