package sfa.model.viewobjects.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 14 11:00:18 IST 2021
// ---------------------------------------------------------------------
public interface ProductsViewRow extends Row {
    BigDecimal getProductid();

    void setProductid(BigDecimal value);

    String getName();

    void setName(String value);

    String getDescription();

    void setDescription(String value);

    BigDecimal getPrice();

    void setPrice(BigDecimal value);

    String getCategory();

    void setCategory(String value);

    BigDecimal getRevenueitem();

    void setRevenueitem(BigDecimal value);
}

