package sfa.model.entities.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 12 09:43:16 IST 2021
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void setFileData(String name, String path, String contTyp);
}

