package sfa.model.viewobjects.staticVo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 02 13:57:48 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AccountTypeImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AccountTypeImpl() {
    }
}

