package sfa.model.viewobjects.staticVo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 19 12:51:03 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AddressTypeImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AddressTypeImpl() {
    }
}

