package sfa.model.viewobjects.staticVo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 15 15:12:38 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductCategoryImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductCategoryImpl() {
    }
}

